"""Phase 8 suppliers and purchase orders."""
from typing import Sequence
import sqlalchemy as sa
from alembic import op
revision="20260827_0006"; down_revision="20260827_0005"; branch_labels: str|Sequence[str]|None=None; depends_on=None
def upgrade():
    op.create_table("suppliers",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("contact_person",sa.String(160)),sa.Column("phone",sa.String(50)),sa.Column("email",sa.String(254)),sa.Column("address",sa.Text()),sa.Column("notes",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index("ix_suppliers_name","suppliers",["name"]); op.create_index("ix_suppliers_is_active","suppliers",["is_active"])
    op.create_table("purchase_orders",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("po_number",sa.String(40),nullable=False),sa.Column("supplier_id",sa.Uuid(),sa.ForeignKey("suppliers.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("order_date",sa.Date(),nullable=False),sa.Column("expected_date",sa.Date()),sa.Column("notes",sa.Text()),sa.Column("subtotal",sa.Numeric(12,2),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("status IN ('DRAFT','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')"))
    for name,cols,unique in [("ix_purchase_orders_po_number",["po_number"],True),("ix_purchase_orders_supplier_id",["supplier_id"],False),("ix_purchase_orders_status",["status"],False),("ix_purchase_orders_order_date",["order_date"],False)]: op.create_index(name,"purchase_orders",cols,unique=unique)
    op.create_table("purchase_order_items",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("purchase_order_id",sa.Uuid(),sa.ForeignKey("purchase_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("product_id",sa.Uuid(),sa.ForeignKey("products.id",ondelete="RESTRICT"),nullable=False),sa.Column("product_name",sa.String(160),nullable=False),sa.Column("sku",sa.String(64),nullable=False),sa.Column("ordered_quantity",sa.Integer(),nullable=False),sa.Column("received_quantity",sa.Integer(),nullable=False,server_default="0"),sa.Column("unit_cost",sa.Numeric(12,2),nullable=False),sa.Column("line_total",sa.Numeric(12,2),nullable=False),sa.CheckConstraint("ordered_quantity > 0"),sa.CheckConstraint("received_quantity >= 0 AND received_quantity <= ordered_quantity"),sa.CheckConstraint("unit_cost >= 0"))
    op.create_index("ix_po_items_po","purchase_order_items",["purchase_order_id"]); op.create_index("ix_purchase_order_items_product_id","purchase_order_items",["product_id"])
def downgrade():
    op.drop_table("purchase_order_items"); op.drop_table("purchase_orders"); op.drop_table("suppliers")
