import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { api } from '../services/api'
import type { Expense, ExpenseCategory, ExpenseInput, ExpenseStatus } from '../types/expense'
import { formatMoney } from '../utils/money'
import { formatLocalDate } from '../utils/reportDates'

const blank = ():ExpenseInput => ({category_id:'',description:'',amount:'',expense_date:formatLocalDate(new Date()),notes:''})

function ExpenseForm({categories,expense,onClose,onSaved}:{categories:ExpenseCategory[];expense:Expense|null;onClose:()=>void;onSaved:()=>void}) {
  const [value,setValue]=useState<ExpenseInput>(expense?{category_id:expense.category_id,description:expense.description,amount:expense.amount,expense_date:expense.expense_date,notes:expense.notes}:blank())
  const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!value.category_id||!value.description.trim()||!value.amount||Number(value.amount)<=0){setError('Category, description, and an amount greater than zero are required.');return}setSaving(true);setError('');try{if(expense)await api.updateExpense(expense.id,value);else await api.createExpense(value);onSaved()}catch(err){setError(err instanceof Error?err.message:'Expense could not be saved.')}finally{setSaving(false)}}
  return <div className="modal-backdrop"><section className="modal card" role="dialog" aria-modal="true" aria-labelledby="expense-title"><h2 id="expense-title">{expense?'Edit Expense':'Add Expense'}</h2><form onSubmit={submit} className="form-grid"><label>Category<select value={value.category_id} onChange={e=>setValue({...value,category_id:e.target.value})} required><option value="">Select category</option>{categories.filter(c=>c.is_active).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Description<input value={value.description} maxLength={255} onChange={e=>setValue({...value,description:e.target.value})} required /></label><label>Amount<input aria-label="Amount" type="number" min="0.01" step="0.01" value={value.amount} onChange={e=>setValue({...value,amount:e.target.value})} required /></label><label>Expense Date<input type="date" value={value.expense_date} onChange={e=>setValue({...value,expense_date:e.target.value})} required /></label><label className="full">Notes<textarea value={value.notes??''} onChange={e=>setValue({...value,notes:e.target.value})} /></label>{error&&<p className="error full" role="alert">{error}</p>}<div className="modal-actions full"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving?'Saving…':'Save Expense'}</button></div></form></section></div>
}

export function ExpensesPage(){
 const [items,setItems]=useState<Expense[]>([]),[categories,setCategories]=useState<ExpenseCategory[]>([]);const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState<ExpenseStatus|''>(''),[from,setFrom]=useState(''),[to,setTo]=useState('');const [page,setPage]=useState(1),[pages,setPages]=useState(0);const [editing,setEditing]=useState<Expense|null|undefined>(undefined),[error,setError]=useState(''),[categoryName,setCategoryName]=useState('')
 const load=useCallback(()=>Promise.all([api.getExpenses({search,categoryId:category,status,startDate:from,endDate:to,page}),api.getExpenseCategories()]).then(([r,c])=>{setItems(r.items);setPages(r.pages);setCategories(c)}).catch(()=>setError('Expenses could not be loaded.')),[search,category,status,from,to,page]);useEffect(()=>{void load()},[load])
 const saved=()=>{setEditing(undefined);void load()};const voidItem=async(item:Expense)=>{const reason=window.prompt('Reason for voiding this expense?');if(!reason?.trim())return;try{await api.voidExpense(item.id,reason);void load()}catch(e){setError(e instanceof Error?e.message:'Expense could not be voided.')}}
 const addCategory=async()=>{if(!categoryName.trim())return;try{await api.createExpenseCategory({name:categoryName});setCategoryName('');void load()}catch(e){setError(e instanceof Error?e.message:'Category could not be added.')}}
 return <div className="page-content expenses-page"><div className="page-heading"><div><span className="eyebrow">Profit operations</span><h1>Operating Expenses</h1><p>Record operating costs separately from inventory purchases and cost of goods sold.</p></div><button className="button primary" onClick={()=>setEditing(null)}>+ Add Expense</button></div>{error&&<div className="error history-error" role="alert">{error}</div>}
 <section className="card expense-filters"><input aria-label="Search expenses" placeholder="Search expense number or description…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><select aria-label="Category filter" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All categories</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}{c.is_active?'':' (inactive)'}</option>)}</select><select aria-label="Status filter" value={status} onChange={e=>{setStatus(e.target.value as ExpenseStatus|'');setPage(1)}}><option value="">All statuses</option><option>ACTIVE</option><option>VOIDED</option></select><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></section>
 <section className="card"><div className="table-wrap"><table><thead><tr><th>Expense</th><th>Category</th><th>Description</th><th>Date</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className={x.status==='VOIDED'?'voided-row':''}><td><strong>{x.expense_number}</strong></td><td>{x.category_name}</td><td>{x.description}{x.void_reason&&<small className="block">Reason: {x.void_reason}</small>}</td><td>{new Date(`${x.expense_date}T00:00:00`).toLocaleDateString()}</td><td>{formatMoney(x.amount)}</td><td><span className={`status-pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{x.status==='ACTIVE'&&<div className="table-actions"><button className="text-button" onClick={()=>setEditing(x)}>Edit</button><button className="text-button danger" onClick={()=>void voidItem(x)}>Void</button></div>}</td></tr>)}</tbody></table></div>{!items.length&&<p className="empty">No expenses found.</p>}<div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages||1}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>
 <section className="card category-manager"><h2>Expense Categories</h2><div className="category-add"><input aria-label="New category name" placeholder="New category" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button className="button secondary" onClick={()=>void addCategory()}>Add Category</button></div><div className="category-chips">{categories.map(c=><span key={c.id} className={!c.is_active?'inactive':''}>{c.name} <button onClick={async()=>{const name=window.prompt('Category name',c.name);if(name?.trim()){await api.updateExpenseCategory(c.id,{name});void load()}}}>Edit</button>{c.is_active&&<button onClick={async()=>{await api.deactivateExpenseCategory(c.id);void load()}}>Deactivate</button>}</span>)}</div></section>
 {editing!==undefined&&<ExpenseForm categories={categories} expense={editing} onClose={()=>setEditing(undefined)} onSaved={saved}/>}</div>
}
