import { useEffect, useState } from 'react'
import { api } from '../services/api'
import type { InventoryStatus, ReportSummary, TopProduct, TrendPoint } from '../types/report'
import { formatMoney } from '../utils/money'
import { getPresetDateRange, type ReportPreset } from '../utils/reportDates'
import { Metrics, TrendChart, zero } from './DashboardPage'

export function ReportsPage() {
  const initial = getPresetDateRange('30'); const [preset, setPreset] = useState<ReportPreset>('30'); const [from, setFrom] = useState(initial[0]); const [to, setTo] = useState(initial[1]); const [range, setRange] = useState<[string, string]>(initial); const [summary, setSummary] = useState<ReportSummary>(zero); const [trend, setTrend] = useState<TrendPoint[]>([]); const [top, setTop] = useState<TopProduct[]>([]); const [stock, setStock] = useState<InventoryStatus | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { setLoading(true); setError(''); Promise.all([api.getReportSummary(...range), api.getSalesTrend(...range), api.getTopProducts(...range), api.getInventoryStatus()]).then(([s, t, p, i]) => { setSummary(s); setTrend(t); setTop(p); setStock(i) }).catch(() => setError('Reports could not be loaded.')).finally(() => setLoading(false)) }, [range])
  const choose = (value: ReportPreset) => { setPreset(value); if (value !== 'custom') { const next = getPresetDateRange(value); setFrom(next[0]); setTo(next[1]); setRange(next) } }
  const apply = () => { if (from > to) { setError('From date cannot be after To date'); return } setRange([from, to]) }
  return <><div className="page-heading"><div><span className="eyebrow">Analytics</span><h1>Reports</h1><p>Authoritative revenue, gross profit, product, and inventory reporting.</p></div></div>
    <section className="card report-filters"><div>{(['today', '7', '30', 'month', 'custom'] as ReportPreset[]).map((p) => <button className={`button ${preset === p ? 'primary' : 'secondary'}`} onClick={() => choose(p)} key={p}>{p === '7' ? 'Last 7 Days' : p === '30' ? 'Last 30 Days' : p === 'month' ? 'This Month' : p[0].toUpperCase() + p.slice(1)}</button>)}</div>{preset === 'custom' && <div className="custom-range"><label>From Date<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To Date<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label><button className="button primary" onClick={apply}>Apply</button></div>}</section>
    {error && <div className="error history-error" role="alert">{error}</div>}{loading ? <p className="loading">Loading reports…</p> : <><Metrics summary={summary} /><p className="average">Average transaction value: <strong>{formatMoney(summary.average_transaction_value)}</strong></p><div className="report-grid"><section className="card report-card wide"><h2>Sales Trend</h2><TrendChart data={trend} /></section><section className="card report-card wide"><h2>Product Performance</h2>{top.length ? <div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Qty Sold</th><th>Revenue</th></tr></thead><tbody>{top.map((p) => <tr key={`${p.product_id}-${p.sku}`}><td><strong>{p.product_name}</strong></td><td>{p.sku}</td><td>{p.quantity_sold}</td><td>{formatMoney(p.revenue)}</td></tr>)}</tbody></table></div> : <p className="empty compact">No sales in this period.</p>}</section><section className="card report-card wide"><h2>Inventory Status</h2><p>{stock?.total_active_products ?? 0} active products · {stock?.total_units_in_stock ?? 0} units in stock</p><div className="inventory-columns"><div><h3>Low Stock</h3>{stock?.low_stock.map(p => <div className="stock-row" key={p.product_id}><span>{p.product_name}<small>{p.sku}</small></span><b>{p.current_stock} / min {p.minimum_stock}</b></div>)}</div><div><h3>Out of Stock</h3>{stock?.out_of_stock.map(p => <div className="stock-row" key={p.product_id}><span>{p.product_name}<small>{p.sku}</small></span><b>0 / min {p.minimum_stock}</b></div>)}</div></div></section></div></>}
  </>
}
