import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, test, vi } from 'vitest'
import App from './App'

const categories = [{id:'cat-1',name:'Utilities',description:null,is_active:true,created_at:'',updated_at:''}]
const recorded = {id:'expense-1',expense_number:'EXP-20260827-A1B2',category_id:'cat-1',category_name:'Utilities',description:'Electricity bill',amount:'1250.00',expense_date:'2026-08-27',notes:null,status:'ACTIVE',created_at:'',updated_at:'',voided_at:null,void_reason:null}
const json = (value:unknown,status=200) => new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}})
function mockExpenses(){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.includes('expense-categories'))return json(categories);if(init?.method==='POST'&&url.endsWith('/api/expenses'))return json(recorded,201);if(url.includes('/void'))return json({...recorded,status:'VOIDED',void_reason:'Duplicate'});if(init?.method==='PATCH')return json({...recorded,description:'Edited bill'});return json({items:[recorded],total:1,page:1,page_size:20,pages:2})})}
afterEach(()=>{cleanup();vi.restoreAllMocks();window.history.pushState({},'','/')})

test('expenses page renders history, filters, categories, and pagination',async()=>{window.history.pushState({},'','/expenses');const fetch=mockExpenses();render(<App/>);expect(await screen.findByText('EXP-20260827-A1B2')).toBeInTheDocument();expect(screen.getAllByText('Utilities').length).toBeGreaterThan(0);fireEvent.change(screen.getByLabelText('Search expenses'),{target:{value:'electric'}});fireEvent.change(screen.getByLabelText('Status filter'),{target:{value:'ACTIVE'}});fireEvent.click(screen.getByRole('button',{name:'Next'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('page=2'),expect.any(Object)))})

test('adds and edits an expense with validation and submission protection',async()=>{window.history.pushState({},'','/expenses');const fetch=mockExpenses();render(<App/>);await screen.findByText('EXP-20260827-A1B2');fireEvent.click(screen.getByRole('button',{name:'+ Add Expense'}));fireEvent.submit(screen.getByRole('button',{name:'Save Expense'}).closest('form')!);expect(await screen.findByRole('alert')).toHaveTextContent('required');fireEvent.change(screen.getByLabelText('Category'),{target:{value:'cat-1'}});fireEvent.change(screen.getByLabelText('Description'),{target:{value:'Water bill'}});fireEvent.change(screen.getByLabelText('Amount'),{target:{value:'50.00'}});fireEvent.click(screen.getByRole('button',{name:'Save Expense'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/api/expenses'),expect.objectContaining({method:'POST'})));fireEvent.click(screen.getAllByRole('button',{name:'Edit'})[0]);fireEvent.change(screen.getByLabelText('Description'),{target:{value:'Edited bill'}});fireEvent.click(screen.getByRole('button',{name:'Save Expense'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/api/expenses/expense-1'),expect.objectContaining({method:'PATCH'})))})

test('voids an expense with a reason',async()=>{window.history.pushState({},'','/expenses');const fetch=mockExpenses();vi.spyOn(window,'prompt').mockReturnValue('Duplicate');render(<App/>);await screen.findByText('EXP-20260827-A1B2');fireEvent.click(screen.getByRole('button',{name:'Void'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/void'),expect.objectContaining({method:'POST',body:JSON.stringify({reason:'Duplicate'})})))})

test('adds, edits, and deactivates categories',async()=>{window.history.pushState({},'','/expenses');const fetch=mockExpenses();vi.spyOn(window,'prompt').mockReturnValue('Power');render(<App/>);await screen.findByText('EXP-20260827-A1B2');fireEvent.change(screen.getByLabelText('New category name'),{target:{value:'Rent'}});fireEvent.click(screen.getByRole('button',{name:'Add Category'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/api/expense-categories'),expect.objectContaining({method:'POST'})));fireEvent.click(screen.getAllByRole('button',{name:'Edit'}).at(-1)!);fireEvent.click(screen.getByRole('button',{name:'Deactivate'}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/api/expense-categories/cat-1'),expect.objectContaining({method:'DELETE'})))})
