import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'

const supplier = { id:'s1', name:'ABC Distributor', contact_person:'Ana', phone:'1', email:null, address:null, notes:null, is_active:true, created_at:'2026-08-27', updated_at:'2026-08-27' }
const product = { id:'p1', name:'Mineral Water', sku:'WATER', barcode:'4801', category_id:'c1', cost_price:'10.00', selling_price:'15.00', current_stock:5, minimum_stock:1, is_active:true, created_at:'', updated_at:'' }
const po = { id:'po1', po_number:'PO-20260827-A1B2', supplier_id:'s1', supplier, status:'DRAFT', order_date:'2026-08-27', expected_date:null, notes:null, subtotal:'20.00', items:[{id:'i1',product_id:'p1',product_name:'Mineral Water',sku:'WATER',ordered_quantity:2,received_quantity:0,unit_cost:'10.00',line_total:'20.00'}],created_at:'',updated_at:'' }
function response(body:unknown){return Promise.resolve({ok:true,json:()=>Promise.resolve(body)}) as Promise<Response>}
function mockApi(overrides:(url:string,init?:RequestInit)=>Promise<Response> = (url)=> url.startsWith('/api/suppliers')?response({items:[supplier],page:1,page_size:20,total_items:1,total_pages:1}):url.startsWith('/api/products')?response([product]):response({items:[po],page:1,page_size:20,total_items:21,total_pages:2})){vi.stubGlobal('fetch',vi.fn(overrides))}

beforeEach(()=>{window.history.pushState({},'', '/purchase-orders');mockApi()})
afterEach(()=>{cleanup();vi.unstubAllGlobals()})

describe('Phase 8 purchasing UI',()=>{
 it('applies all PO filters, resets page, and paginates',async()=>{render(<App/>);await screen.findByText('PO-20260827-A1B2');fireEvent.change(screen.getByLabelText('PO Number'),{target:{value:'A1B2'}});fireEvent.change(screen.getByLabelText('Supplier filter'),{target:{value:'s1'}});fireEvent.change(screen.getByLabelText('Status filter'),{target:{value:'ORDERED'}});fireEvent.change(screen.getByLabelText('From date'),{target:{value:'2026-08-01'}});fireEvent.change(screen.getByLabelText('To date'),{target:{value:'2026-08-27'}});fireEvent.click(screen.getByText('Apply'));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('search=A1B2'),expect.anything()));fireEvent.click(screen.getByText('Next'));await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining('page=2'),expect.anything()))})
 it('searches products and creates a draft with preview total',async()=>{window.history.pushState({},'','/purchase-orders/new');render(<App/>);await screen.findByText('New Purchase Order');fireEvent.change(screen.getByLabelText('Search products'),{target:{value:'4801'}});fireEvent.change(screen.getByLabelText('Product result'),{target:{value:'p1'}});fireEvent.click(screen.getByText('Add Product'));expect(screen.getByText('PO Total ₱10.00')).toBeInTheDocument()})
 it('shows Edit for drafts and opens receiving for ordered POs',async()=>{window.history.pushState({},'','/purchase-orders?id=po1');mockApi((url)=>url==='/api/purchase-orders/po1'?response(po):url.startsWith('/api/suppliers')?response({items:[supplier]}):response([product]));const firstRender=render(<App/>);expect(await screen.findByText('Edit')).toHaveAttribute('href','/purchase-orders/edit?id=po1');firstRender.unmount();vi.unstubAllGlobals();mockApi((url)=>url==='/api/purchase-orders/po1'?response({...po,status:'ORDERED'}):url.startsWith('/api/suppliers')?response({items:[supplier]}):response([product]));render(<App/>);fireEvent.click(await screen.findByText('Receive Stock'));expect(screen.getByText('Confirm Stock Receipt')).toBeInTheDocument();expect(screen.getByDisplayValue('2')).toHaveAttribute('max','2')})
 it('creates, edits, and deactivates suppliers with safe API errors',async()=>{window.history.pushState({},'','/suppliers');render(<App/>);await screen.findByText('ABC Distributor');fireEvent.click(screen.getByText('Edit'));expect(screen.getByDisplayValue('ABC Distributor')).toBeInTheDocument();fireEvent.click(screen.getByText('Deactivate'));await waitFor(()=>expect(fetch).toHaveBeenCalledWith('/api/suppliers/s1',expect.objectContaining({method:'DELETE'})))})
})
