import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, test, vi } from 'vitest'
import App from './App'

const summary = { sales_total: '4250.00', transaction_count: 31, items_sold: 104, gross_profit: '1380.00', profit_complete: true, average_transaction_value: '137.10', total_active_products: 2, total_units_in_stock: 8, low_stock_count: 1, out_of_stock_count: 1 }
const trend = [{ date: '2026-08-26', sales: '0.00', transactions: 0, items_sold: 0 }, { date: '2026-08-27', sales: '4250.00', transactions: 31, items_sold: 104 }]
const top = [{ product_id: '1', product_name: 'Coca-Cola', sku: 'COKE', quantity_sold: 43, revenue: '1075.00' }]
const stock = { total_active_products: 2, total_units_in_stock: 8, low_stock: [{ product_id: '1', product_name: 'Mineral Water', sku: 'WATER', current_stock: 2, minimum_stock: 5 }], out_of_stock: [] }
const response = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } })
function mockReports(fail = false) { return vi.spyOn(globalThis, 'fetch').mockImplementation(async input => { if (fail) return response({}, 500); const url = String(input); if (url.includes('sales-trend')) return response(trend); if (url.includes('top-products')) return response(top); if (url.includes('inventory-status')) return response(stock); return response(summary) }) }
afterEach(() => { cleanup(); vi.restoreAllMocks(); window.history.pushState({}, '', '/') })

test('dashboard renders authoritative summary, peso values, trend, products, and low stock', async () => { window.history.pushState({}, '', '/dashboard'); mockReports(); render(<App />); expect(await screen.findByText('₱4,250.00')).toBeInTheDocument(); expect(screen.getByText('31')).toBeInTheDocument(); expect(screen.getByText('Coca-Cola')).toBeInTheDocument(); expect(screen.getByText('Mineral Water')).toBeInTheDocument(); expect(screen.getByLabelText('Sales trend chart')).toBeInTheDocument() })
test('dashboard handles errors', async () => { window.history.pushState({}, '', '/dashboard'); mockReports(true); render(<App />); expect(await screen.findByRole('alert')).toHaveTextContent('Dashboard could not be loaded.') })
test('reports renders sections and switches presets and custom range', async () => { window.history.pushState({}, '', '/reports'); const fetchMock = mockReports(); render(<App />); expect(await screen.findByText('Product Performance')).toBeInTheDocument(); expect(screen.getByText('Average transaction value:')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Last 7 Days' })); await waitFor(() => expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('start_date='), expect.any(Object))); fireEvent.click(screen.getByRole('button', { name: 'Custom' })); fireEvent.change(screen.getByLabelText('From Date'), { target: { value: '2026-08-28' } }); fireEvent.change(screen.getByLabelText('To Date'), { target: { value: '2026-08-27' } }); fireEvent.click(screen.getByRole('button', { name: 'Apply' })); expect(screen.getByRole('alert')).toHaveTextContent('From date cannot be after To date') })
